/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#21008e",
        "on-error": "#690005",
        "surface-variant": "#353437",
        "outline": "#928fa0",
        "secondary-fixed": "#e4dfff",
        "surface-container-lowest": "#0e0e10",
        "surface-container": "#201f21",
        "background": "#131315",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#e4dfff",
        "tertiary": "#ffb86a",
        "on-primary-fixed": "#150066",
        "on-tertiary-container": "#3f2300",
        "surface-container-high": "#2a2a2c",
        "on-background": "#e5e1e4",
        "surface-bright": "#39393b",
        "surface-tint": "#c6c0ff",
        "on-primary": "#2700a1",
        "tertiary-fixed": "#ffdcbc",
        "on-primary-fixed-variant": "#3f2bb8",
        "primary-fixed-dim": "#c6c0ff",
        "on-surface-variant": "#c8c4d6",
        "tertiary-container": "#cc7f17",
        "on-secondary-fixed": "#191343",
        "surface-container-low": "#1b1b1d",
        "inverse-on-surface": "#313032",
        "secondary-container": "#454075",
        "outline-variant": "#474554",
        "tertiary-fixed-dim": "#ffb86a",
        "surface-dim": "#131315",
        "primary-container": "#8b80ff",
        "primary": "#c6c0ff",
        "on-secondary-container": "#b4aeeb",
        "surface": "#131315",
        "inverse-primary": "#5748d0",
        "on-secondary": "#2e2a5d",
        "on-surface": "#e5e1e4",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#683d00",
        "on-secondary-fixed-variant": "#454075",
        "on-tertiary-fixed": "#2c1700",
        "on-tertiary": "#492900",
        "secondary-fixed-dim": "#c6c0fd",
        "secondary": "#c6c0fd",
        "inverse-surface": "#e5e1e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      boxShadow: {
        "top-nav": "0 20px 40px rgba(0, 0, 0, 0.4)",
      },
    },
  },
  plugins: [],
};

export default config;
